- name: Validate criticality_score installation
  stat:
    path: "{{ lookup('env','GOPATH') }}/bin/criticality_score"
  register: criticality_file


- name: Print message
  debug:
    msg: Criticality score is not installed 
  when: not criticality_file.stat.exists

- name: Remove criticality_score
  shell: rm "{{ lookup('env','GOPATH') }}/bin/criticality_score"
  when: criticality_file.stat.exists

- name: Unset github token
  shell: unset GITHUB_AUTH_TOKEN

- name: Check if go is available
  shell: go version
  failed_when: false
  register: go_check

- name: Print msg
  debug:
    msg: go not installed
  when: go_check.stdout == ''

- name: Remove Go
  become: yes
  shell: |
    snap remove go
    rm -rf "{{ lookup('env','GOPATH') }}"
  when: go_check.stdout != ''

  