- name: Check if snap present
  shell: snap --version
  register: snap_check

- name: Print message
  debug:
    msg: "Snap already present {{ snap_check.msg }}"
  when: snap_check.msg != ''

- name: Install snap
  become: yes
  apt:
    name: snapd
    state: present
  when: snap_check.msg == ''


- name: Check if go exists
  shell: go version
  register: go_check

- name: Print message
  debug:
    msg:" Go already exists {{ go_check.msg }}"
  when: go_check.msg != ''

- name: Install Go
  become: yes
  shell: |
    snap install --classic --channel={{ go_version }}/{{ go_channel }} go
    export GOPATH=$HOME/go
    export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
  when: go_check.msg == ''
  
- name: Check if criticality_score present
  shell: criticality_score --help
  register: criticality_check
  failed_when: false

- name: Print msg
  debug:
    msg: "Msg: {{ criticality_check.msg }}"

- name: Print message
  debug:
    msg: criticality_score already installed
  when: criticality_check.msg != ''

- name: Install criticality_score
  become: yes
  shell: "go install github.com/ossf/criticality_score/cmd/criticality_score@{{ criticality_score_version }}"
  when: criticality_check.msg == ''

- name: Checking if github auth token available
  debug:
    msg: Github auth token is available
  when: lookup('env','BESMAN_GH_TOKEN') != ''

- name: Setting Github Auth token
  shell: "export GITHUB_AUTH_TOKEN={{ lookup('env','BESMAN_GH_TOKEN') }}"
  when: lookup('env','BESMAN_GH_TOKEN') != ''
