- name: Check if snap present
  shell: snap --version
  failed_when: false
  register: snap_check

- name: Print message
  debug:
    msg: "Snap already present {{ snap_check.stdout }}"
  when: snap_check.stdout != ''

- name: Install snap
  become: yes
  apt:
    name: snapd
    state: present
  when: snap_check.stdout == ''


- name: Check if go exists
  shell: go version
  failed_when: false
  register: go_check

- name: Print message
  debug:
    msg: "Go already exists {{ go_check }}"
  failed_when: false
  when: go_check.stdout != ''

- name: Install Go
  become: yes
  command: snap install --classic --channel="{{ go_version }}"/"{{ go_channel }}" go
  when: go_check.stdout == ''

- name: Exporting paths
  become: yes
  shell: |
    echo "export GOPATH=$HOME/go" >> ~/.bashrc
    echo "export PATH=$PATH:/usr/local/go/bin:$GOPATH/bin" >> ~/.bashrc
  
- name: Check if criticality_score present
  shell: criticality_score --help
  register: criticality_check
  failed_when: false

- name: Print msg
  debug:
    msg: "Msg: {{ criticality_check.stdout }}"
  when: criticality_check.stdout != ''


- name: Print message
  debug:
    msg: criticality_score already installed
  when: criticality_check.stdout != ''

- name: Install criticality_score
  become: yes
  shell: go install github.com/ossf/criticality_score/cmd/criticality_score@"{{ criticality_score_version }}"
  when: criticality_check.stdout == '' and go_check.stdout != ''

- name: Checking if github auth token available
  debug:
    msg: Github auth token is available
  when: lookup('env','BESMAN_GH_TOKEN') != ''

- name: Setting Github Auth token
  shell: "export GITHUB_AUTH_TOKEN={{ lookup('env','BESMAN_GH_TOKEN') }}"
  when: lookup('env','BESMAN_GH_TOKEN') != ''
